config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[new create destroy]
  namespace :services do
    resources :weather, only: :index
  end
  namespace :backoffice do
    resources :admins
    resources :pages, except: :show 
    resources :categories, except: :show
    resources :posts do
      get ':id/gallery', to: 'posts#gallery', on: :collection, as: :gallery
    end
    resources :galleries, only: %i[show create destroy]
    resources :banners do
      get 'render_html/:id', on: :collection, to: 'banners#banner_render'
    end
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV.fetch('SIDEKIQ_USERNAME', 'admin'))) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV.fetch('SIDEKIQ_PASSWORD', '123456')))
  end if Rails.env.production?
  mount Sidekiq::Web => 'sidekiq'
  root to: 'frontend/home#index'
  get '/noticias', to: 'frontend/posts#index', as: :posts
  get '/:slug', to: 'frontend/posts#show', as: :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :page, optional: true

  acts_as_taggable_on :tags
  acts_as_taggable_on :skills, :interests

  has_many :post_categories, dependent: :destroy
  has_many :categories, through: :post_categories
  has_many :galleries, dependent: :destroy
  has_many :hits, class_name: 'PostHit', dependent: :destroy, source: :post

  scope :published, -> { where(active: true) }
  scope :feature_posts, -> { where(feature_post: true, active: true) }
  scope :by_category, lambda { |category|
    joins(:post_categories).where('post_categories.category_id = :category_id OR posts.page_id = :page_ids',
                                  category_id: category.id, page_ids: category.pages.ids)
                           .distinct('posts.id')
  }

  extend FriendlyId
  friendly_id :name, use: :slugged

  has_one_attached :image
  has_one_attached :cover

  validates :name, :body, presence: true
  validates :name, :subname, :cover_subtitle, :image_subtitle, length: { maximum: 140 }
  validates :headline, length: { maximum: 100 }
  validates :summary, length: { maximum: 250 }
  # validates :category_ids, presence: true
  validates :cover, :image, content_type: %w[image/png image/gif image/jpg image/jpeg],
                            size: { less_than: 10.megabytes }

  def self.top_hits(limit: 10)
    week = (Time.current - 7.days).strftime('%Y-%m-%d')
    query = 'SELECT posts.*, SUM(p_hits.hits) AS total_hits FROM posts '\
            'INNER JOIN post_hits AS p_hits ON p_hits.post_id = posts.id WHERE p_hits.hit_day > :week '\
            'GROUP BY posts.id ORDER BY total_hits DESC LIMIT :limit'
    Post.find_by_sql(sanitize_sql_array([query, { limit: limit, week: week }]))
  end
end

app/controllers/backoffice/admins_controller.rb
module Backoffice
  class AdminsController < BackofficeController
    before_action :set_admin, only: %i[show edit update destroy]

    def index
      @q = Admin.ransack(params[:q])
      @admins = @q.result.page(params[:page]).per(params[:size])
    end

    def show; end

    def new
      @admin = Admin.new
    end

    def create
      @admin = Admin.new(page_params)
      if @admin.save
        redirect_to backoffice_admins_path, notice: I18n.t('controller.messages.success.create')
      else
        render :new
      end
    end

    def edit; end

    def update
      if @admin.update(page_params)
        redirect_to backoffice_admins_path, notice: I18n.t('controller.messages.success.update')
      else
        render :edit
      end
    end

    def destroy
      @admin.destroy
      redirect_to backoffice_admins_path, notice: I18n.t('controller.messages.success.destroy')
    end

    private

    def set_admin
      @admin = Admin.find(params[:id])
    end

    def page_params
      params.require(:admin).permit(:name, :email, :password, :password_confirmation, :active, :profile)
    end
  end
end

app/controllers/backoffice/banners_controller.rb
module Backoffice
  class BannersController < BackofficeController
    before_action :set_banner, only: %i[show edit update destroy]

    def index
      @q = Banner.ransack(params[:q])
      @banners = @q.result.page(params[:page]).per(params[:size])
    end

    def show; end

    def new
      @banner = Banner.new
    end

    def create
      @banner = Banner.new(page_params)
      if @banner.save
        redirect_to backoffice_banners_path, notice: I18n.t('controller.messages.success.create')
      else
        render :new
      end
    end

    def edit; end

    def update
      if @banner.update(page_params)
        redirect_to backoffice_banners_path, notice: I18n.t('controller.messages.success.update')
      else
        render :edit
      end
    end

    def destroy
      @banner.destroy
      redirect_to backoffice_banners_path, notice: I18n.t('controller.messages.success.destroy')
    end

    private

    def set_banner
      @banner = Banner.find(params[:id])
    end

    def page_params
      params.require(:banner).permit(:name, :banner, :date_start, :date_end, :kind, :active)
    end
  end
end

app/controllers/backoffice/categories_controller.rb
module Backoffice
  class CategoriesController < BackofficeController
    before_action :set_category, only: %i[show edit update destroy]

    def index
      @q = Category.ransack(params[:q])
      @categories = @q.result.page(params[:page]).per(params[:size])
    end

    def new
      @category = Category.new
    end

    def create
      @category = Category.new(category_params)
      if @category.save
        redirect_to backoffice_categories_path, notice: 'Criado com sucesso'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @category.update(category_params)
        redirect_to backoffice_categories_path, notice: 'Atualizado com sucesso'
      else
        render :edit
      end
    end

    def destroy
      @category.destroy
      redirect_to backoffice_categories_path, notice: 'Excluida com sucesso'
    end

    private

    def set_category
      @category = Category.friendly.find(params[:id])
    end

    def category_params
      params.require(:category).permit(:name, :show_on_home)
    end
  end
end

app/controllers/backoffice/galleries_controller.rb
module Backoffice
  class GalleriesController < BackofficeController
    before_action :set_gallery_item, only: %i[show destroy]
    skip_before_action :verify_authenticity_token, only: :create

    def show
      render layout: false
    end

    def create
      @gallery = Gallery.create(gallery_params)
      if @gallery.save
        render json: @gallery, status: :created
      else
        render json: @gallery.errors, status: :unprocessable_entity
      end
    end

    def destroy
      @gallery.destroy
      redirect_to gallery_backoffice_posts_path(@gallery.post_id), notice: 'Excluida com successo'
    end

    private

    def set_gallery_item
      @gallery = Gallery.find(params[:id])
    end

    def gallery_params
      params.require(:gallery).permit(:post_id, :image)
    end
  end
end

app/controllers/backoffice/pages_controller.rb
module Backoffice
  class PagesController < BackofficeController
    before_action :set_page, only: %i[edit update destroy]

    def index
      @q = Page.ransack(params[:q])
      @pages = @q.result.page(params[:page]).per(params[:size])
    end

    def new
      @page = Page.new
    end

    def create
      @page = Page.new(page_params)
      if @page.save
        redirect_to backoffice_pages_path, notice: 'Criado com successo'
      else
        render :new
      end
    end

    def edit; end

    def update
      if @page.update(page_params)
        redirect_to backoffice_pages_path, notice: 'Atualizado com successo'
      else
        render :edit
      end
    end

    def destroy
      @page.destroy
      redirect_to backoffice_pages_path, notice: 'Excluida com successo'
    end

    private

    def set_page
      @page = Page.friendly.find(params[:id])
    end

    def page_params
      params.require(:page).permit(:name)
    end
  end
end

app/controllers/backoffice/posts_controller.rb
module Backoffice
  class PostsController < BackofficeController
    before_action :set_post, only: %i[update edit show destroy gallery]
    before_action :set_categories_and_pages, only: %i[edit new create update]

    def index
      @q = Post.ransack(params[:q])
      @q.sorts = 'id desc' if @q.sorts.empty?
      @posts = @q.result.page(params[:page]).per(params[:size])
    end

    def show; end

    def new
      @post = Post.new
    end

    def create
      @post = Post.new(post_params)
      if @post.save
        redirect_to backoffice_posts_path, notice: I18n.t('controller.messages.success.create')
      else
        render :new
      end
    end

    def gallery
      render layout: false if request.xhr?
    end

    def edit; end

    def update
      if @post.update(post_params)
        redirect_to backoffice_posts_path, notice: I18n.t('controller.messages.success.update')
      else
        render :edit
      end
    end

    def destroy
      @post.destroy
      redirect_to backoffice_posts_path, notice: I18n.t('controller.messages.success.destry')
    end

    private

    def set_post
      @post = Post.friendly.find(params[:id])
    end

    def set_categories_and_pages
      @categories = Category.all.order(name: :asc)
      @pages = Page.all.order(name: :asc)
    end

    def post_params
      params.require(:post).permit(:name, :subname, :headline,
                                   :cover, :image, :body, :active, :url_video, :image_subtitle,
                                   :cover_subtitle, :feature_post, :summary, :tag_list, :page_id,
                                   category_ids: [])
    end
  end
end

app/controllers/backoffice_controller.rb
class BackofficeController < ApplicationController
  before_action :require_login
end

app/controllers/frontend/posts_controller.rb
module Frontend
  class PostsController < FrontendController
    before_action :set_post, only: :show
    def index
      @q = Post.published.ransack(params[:q])
      @q.sorts = 'id desc' if @q.sorts.empty?
      @posts = @q.result.page(params[:page]).per(params[:size])
    end

    def show
      @post.hits.find_or_create_by(hit_day: Time.current.to_date).tap do |post|
        post.increment!(:hits)
      end
    end

    private

    def set_post
      @post = Post.published.friendly.find(params[:slug])
    end
  end
end

app/views/backoffice/posts/_form.html.erb
<%= javascript_include_tag Ckeditor.cdn_url %>
<%= simple_form_for([:backoffice, @post], html: { multipart: true } ) do |f| %>
  <div class='row'>
    <div class='col-md-6'>
      <%= f.association :page, collection: @pages, prompt: 'Selecione uma página', include_blank: true, input_html: { class: 'select2' }, label: 'Página' %>
    </div>
    <div class='col-md-6'>
      <%= f.association :categories, collection: @categories, input_html: { multiple: true, class: 'select2' }, label: 'Categorias' %>
    </div>
  </div>
  <div class='row'>
   <div class='col-md-6'>
    <%= f.input :image, as: :file %>
    <%= f.input :image_subtitle %>
    <% if @post.image.attached? %>
      <%= image_tag(url_for(@post.image.variant(resize: '120x120'))) %>
    <% end %>
   </div>
    <div class='col-md-6'>
      <%= f.input :cover, as: :file %>
      <%= f.input :cover_subtitle %>
      <% if @post.cover.attached? %>
        <%= image_tag(url_for(@post.cover.variant(resize: '120x120'))) %>
      <% end %>
    </div>
  </div>
  <%= f.input :name %>
  <div class='row'>
    <div class='col-md-6'>
      <%= f.input :subname %>
    </div>
    <div class='col-md-6'>
      <%= f.input :headline %>
    </div>
  </div>
  <%= f.input :summary, as: :text %>
  <%= f.input :body, as: :ckeditor, input_html: { ckeditor: { toolbar: 'Full', height: 400 } } %>
  <%= f.input :active, as: :boolean, input_html: { data: { toggle: 'toggle', size: 'sm'} } %>
  <%= f.input :feature_post, as: :boolean, input_html: { data: { toggle: 'toggle', size: 'sm'} } %>
    <div class='row'>
    <div class='col-md-6'>
      <%= f.input :url_video %>
    </div>
    <div class='col-md-6'>
      <%= f.input :tag_list, :input_html => { class: 'tagsinput form-control', value: @post.tag_list.join(', ') }, label: 'Tags' %>
    </div>
  </div>
  <%= f.button :submit, class: 'btn-success' %>
<% end %>

app/views/backoffice/posts/_gallery.html.erb
<div class='row gallery'>
  <% @post.galleries.each do |row| %>
    <div class='col-md-3'>
      <div class="card">
        <%= image_tag(url_for(row.image.variant(resize: '500x500')), class: 'card-img-top') %>
        <div class="card-body text-center">
          <%= link_to  'deletar', backoffice_gallery_path(row), class: 'btn btn-sm btn-danger', method: 'delete' %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/backoffice/posts/edit.html.erb
<h1>Editar: <%= @post.name %></h1>
<%= render 'form' %>

app/views/backoffice/posts/gallery.html.erb
<h1><%= @post.name %></h1>
<form action="<%= backoffice_galleries_url %>" class="dropzone" id='imageUpload' method='post'>
  <div class="dz-message" data-dz-message><span>Arraste ou clique para procurar as imagens</span></div>
  <input type='hidden' value="<%= @post.id %>" name="[gallery]post_id">
  <div class="fallback">
    <input name="image" type="file" multiple />
  </div>
</form>
<%= render partial: 'gallery' %>

app/views/backoffice/posts/index.html.erb
<%= render partial: 'backoffice/shared/header_add', locals: { path: new_backoffice_post_path } %>
<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col"><%= sort_link(@q, :id, '#', default_order: :desc) %></th>
      <th scope="col"><%= sort_link(@q, :name, 'Título', default_order: :desc) %></th>
      <th scope="col"><%= sort_link(@q, :created_at, 'Criado', default_order: :desc) %></th>
      <th scope="col"><%= sort_link(@q, :updated_at, 'Atualizado', default_order: :desc) %></th>
      <th scope="col">Capa</th>
      <th scope="col" class='text-center'>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <th scope="row"><%= post.id %></th>
        <td><%= post.name.truncate(100, separator: ' ') %></td>
        <td><%= post.created_at.time.to_formatted_s(:long) %></td>
        <td><%= post.updated_at.time.to_formatted_s(:long) %></td>
        <td>
        <%= image_tag(url_for(post.cover.variant(resize: "120x120"))) if post.cover.attached? %>
        </td>
        <td class='text-center'style="width:  20%">
            <%= link_to 'Exibir', backoffice_post_path(post), class: 'btn btn-success btn-sm' %>
            <%= link_to 'Editar', edit_backoffice_post_path(post), class: 'btn btn-primary btn-sm' %>
            <%= link_to 'Galeria', gallery_backoffice_posts_path(post), class: 'btn  btn-info btn-sm' %>
            <%= link_to 'Excluir', backoffice_post_path(post), method: :delete, class: 'btn btn-danger btn-sm' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="d-flex justify-content-center">
  <%= paginate @posts %>
</div>

app/views/backoffice/posts/new.html.erb
<h1>Criar post</h1>
<%= render 'form' %>

app/views/backoffice/posts/show.html.erb
<div class='body'>
<h1><%= @post.name %></h1>
<%= content_tag(:h2, @post.headline) if @post.headline.present? %>
<%= content_tag(:summary, @post.summary) if @post.summary.present? %>
<%= image_tag(url_for(@post.cover), class: 'img-fluid') if @post.cover.attached? %>
<div class='text'><%= @post.body.html_safe? %></div>
<%= content_tag(:span, "Categorias: #{@post.categories.pluck(:name).join(', ')}") if @post.categories.present? %>
</div>