config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :sessions, only: %i[new create destroy]
  namespace :services do
    resources :weather, only: :index
  end
  namespace :backoffice do
    resources :admins
    resources :pages, except: :show 
    resources :categories, except: :show
    resources :posts do
      get ':id/gallery', to: 'posts#gallery', on: :collection, as: :gallery
    end
    resources :galleries, only: %i[show create destroy]
    resources :banners do
      get 'render_html/:id', on: :collection, to: 'banners#banner_render'
    end
  end

  Sidekiq::Web.use Rack::Auth::Basic do |username, password|
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV.fetch('SIDEKIQ_USERNAME', 'admin'))) &
      ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV.fetch('SIDEKIQ_PASSWORD', '123456')))
  end if Rails.env.production?
  mount Sidekiq::Web => 'sidekiq'
  root to: 'frontend/home#index'
  get '/noticias', to: 'frontend/posts#index', as: :posts
  get '/:slug', to: 'frontend/posts#show', as: :post
end

app/views/layouts/partials/_header.html.erb
<header class='page-header'>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <a class="navbar-brand" href="#">Home</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item <%= menu_current_link if controller_name == 'posts' %>">
          <a class="nav-link" href="<%= backoffice_posts_url %>">Posts</a>
        </li>
        <li class="nav-item <%= menu_current_link if controller_name == 'banners' %>">
          <a class="nav-link" href="<%= backoffice_banners_url %>">Banners</a>
        </li>
        <li class="nav-item <%= menu_current_link if controller_name == 'categories' %>">
          <a class="nav-link" href="<%= backoffice_categories_url %>">Categorias</a>
        </li>
        <li class="nav-item <%= menu_current_link if controller_name == 'pages' %>">
          <a class="nav-link" href="<%= backoffice_pages_url %>">Páginas</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="<%= session_path('me')%>" data-method='delete'>Sair</a>
        </li>
      </ul>
    </div>
  </nav>
</header>